### ISSUE TITLE
Suggestions for adding uncompressed source code

### ISSUE THREAD

**Issue by yusuftaufiq** [41pha1/spicetify-romaji-lyrics#3]
This project looks interesting and promising. If possible, I would like to suggest adding uncompressed source code so that everyone can learn the source code in this repository and start contributing easily.

**Comment by 41pha1** [comment]
Thank you for your interest in this project!
I have cleaned the code a little and added an uncompressed version in the marketplace folder.
If your interested in the inner workings of the translation part, have a look at the Kuroshiro language library for JS that has been used here.

**Comment by yusuftaufiq** [comment]
> Thank you for your interest in this project! I have cleaned the code a little and added an uncompressed version in the marketplace folder. If your interested in the inner workings of the translation part, have a look at the Kuroshiro language library for JS that has been used here.

Thanks! That looks a lot better, I'll close this issue and will open an issue/PR in the future if there are any ideas or suggestions I can pass on.
